- navigator.js
- scratch.js
- tiling.js
Let every window have a clone (made on `window-created`). The clone lives in a workspace specific container. When doing animations we hide the WindowActors and animate the clones instead. When animations are done we hide the clone and show the WindowActor if the window position is placed in a _possible_ position.
The most obvious benefit is getting rid of the weird stack on the sides. Windows can instead be cleanly placed one after each other.
Another benefit is making workspace animations override-able by simply hiding all `WindowActors` and moving the clone containers around instead. This means we can do stuff like making an android style workspace mru.
> Use clones for all animations, fixing a bunch of underlying issues

- app.js
- extension.js
- kludges.js
- liveAltTab.js
- minimap.js
- navigator.js
- notes.org
- scratch.js
- stackoverlay.js
- tiling.js
- topbar.js
- When changing monitors the active workspace will follow the primary monitor, the remaining monitors will be populated with the top of the workspace mru.
- The workspace mru stack is shared between all monitors, scaled to fit the monitor accessing the stack.
- Non active monitors are covered in a overlay which will activate the corresponding workspace when detecting the mouse pointer. It seems like there's no `pointer-entered-monitor`.
- When changing to another visible workspace the pointer will warp to the center of its monitor.
We create an actor spanning the whole screen, `Spaces.spaceContainer` which holds all spaces. A `Space` is now first contained in a `Space.clip` container clipping away anything that protrudes from the monitor. The `cloneContainer` is then moved within the …
> Multimonitor support

- navigator.js
I'm using paperwm without coloring each workspace (actually I'm using other extension which changes wallpaper on workspace change). In that case I can see workspace previews in background (especially if target workspace is empty).
This change hides previews when workspace change was done
> Hide window previews after workspace was selected

- navigator.js
- stackoverlay.js
- tiling.js
Better multi monitor support. In particular persist the monitor layout when eg. locking and unlocking gnome-shell.
fixes #58 
Also add basic support for `workspaces-only-on-primary` by putting all the spaces on the primary monitor leaving the rest of the monitors with a regular layout.
closes #57
> Restore monitor setup on disable/enable

- minimap.js
- navigator.js
- stackoverlay.js
- tiling.js
- utils.js
This is somewhat large rewrite of the scroll and layout functionality.
Instead of laying out all the clones and windows when on eg. running `ensureVievport` we now move the `scrollContainer`, syncing the MetaWindow positions when animations are done.
This makes scrolling consistently smooth and easier to deal with, though it does require some simple math doing coordinate transforms.
> Refactor scrolling 

- README.md
- examples/keybindings.js
- extension.js
- keybindings.js
- liveAltTab.js
- navigator.js
- utils.js
Some ramblings:
An action is simply a described function that can be invoked by the user with context depending arguments. The actual function is called the action handler.
Same as (interactive) functions in emacs.
The handler have a defined interface\: (not yet stabilized)
`handler(selectedWindow, selectedSpace, ...)`
opensNavigator: open the navigator on invocation (when invoked through a binding)
activeInNavigator: action makes sense when navigator is open
activeInScratch: action makes sense when the scratch layer have focus
It makes sense to slightly alter what the action does depending on how it's invoked(?)
The example in mind is actions that opens the navigator: currently it doesn't make sense to open it unless invoked through a binding since the navigator can only be open while …
> Refactor interal keybinding API and support schemaless/user-defined keybindings

- README.md
- schemas/org.gnome.shell.extensions.org-scrollwm.gschema.xml
Fix minor spelling and grammar mistakes in README.md and the workspace colors label in gschema.xml.
> Fix some minor typos/spelling in documentation

- tiling.js
Slurp now pushes the active window into the column to the left
if there is no column to the right.
This allows freshly created windows to be stacked without
having to change focus.
> Improve Slurp behaviour with freshly created windows

- keybindings.js
- liveAltTab.js
- tiling.js
- utils.js
Replace the current alt-tab behavior (which will go a bunch of back and forth) with having instant previews of the window at the actual position it will land if selected.
> Alt tab with instant preview

- README.md
- liveAltTab.js
- metadata.json
- minimap.js
- navigator.js
- prefs.js
- scratch.js
- stackoverlay.js
- tiling.js
- topbar.js
- utils.js
- Upstream now mostly use `class` which `Last.Class` can't extend see https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361
- Extending GObject classes is still possible with `Lang.Class`
- Extending js classes that extends GObject classes now require wrapping with `GObject.registerClass`
- Blur causes rendering issues, where things simply fail to render.
- `set_child_above_sibling` now skips asserts when using a release build of mutter, this makes for some truly strange behavior. The child would be removed from the parent, but the parent link would remain. Simply avoid setting actors above/below themselves.
Known issues:
> Port to 3.32

- examples/keybindings.js
I tried using this example and got an error because `i` should be `k`. With this change it works for me.
Thanks for the great tool! I'm really enjoying it so far.
> Fix typo in keybindings example

- tiling.js
If the indices isn't synced a disable/enable cycle will jumple the workspace
names/backgrounds
> Sync space settings on workspace changes

- tiling.js
- utils.js
Windows sometimes was registered (`registerWindow`) twice on startup (observed
on X11 3.28) causing all sorts of problems.
Seems like the extension sometimes is enabled/disabled twice on startup causing
the 'startup-complete' signal to be connected twice. Use the `Signals` class to
manage the signal to guard against this scenario.
I added a one-shot function to `Signals` since it's an error to disconnect an
already disconnected signal and that would happen on disable if the
'startup-complete' signal disconnected the signal itself.
assoc: d8069078f2bbad01a73b72bf2e4ddaf08ca0f585
> Ensure 'startup-complete' is not connected twice

- tiling.js
I find it very annoying when trying to do cycleWidth and nothing is happening. This is usually caused by the window being maximized for some reason. Simply cheeking if it is, and if so unmaximizing it, is a simple fix that works well.
> Unmaximize window on cycleWidth

- topbar.js
Hi,
when using a theme that messes with the style/positioning of the topbar, the label of the spaces won't perfectly position. For example with the Sweet-Dark shell theme:
Instead of trying to re-position it so it overlaps nicely, I just completely hid it, as I don't see any use for the label:
Cheers
> Remove unneded topbar workspace label

- tiling.js
When switching between monitors, we can get into a situation where windows
aren't taking mouse input, looks like a weird x11 bug.
fixes #111
> x11: force a layout on workspace switch

- set-recommended-gnome-shell-settings.sh
We now support dynamic workspaces well, so there's no longer a good reason to
prefer static workspaces by default.
I've been using dynamic workspaces for a while now and can't see anything really wrong with it anymore. Workspaces that are commonly in use tends to be prioritized which is exactly what one wants.
> set-recommended-gnome-shell-settings: do not prefer static workspaces

- examples/keybindings.js
- extension.js
- gestures.js
- keybindings.js
- kludges.js
- liveAltTab.js
- minimap.js
- navigator.js
- scratch.js
- settings.js
- stackoverlay.js
- tiling.js
- topbar.js
- utils.js
`extenstionUtils.extensions` is undefined in 3.34 and thus crashes the extension.
`extensionUtils.getCurrentExtension();` was previously used in some places so I assume that it also exists in older versions or otherwise the current version of the extension should have already crashed there.
Window placement is messed up as well so this does not give full 3.34 compatibility but not crashing is a start.
> Fix crash under Gnome 3.34

- Settings.ui
- prefs.js
We previously wrapper the `notebook` in a `ScrolledWindow` which made the tab bar scroll. Move scrolling into the keybinding tab (don't think it's necessary to have any in the other tabs).  Also made the search bar sticky.
The default tree view search doesn't work and can pop up outside the scroll so
disable it.
TODO: add something like `ctrl-f`, `/` to focus the search input
> prefs: don't scroll the tabs

- tiling.js
ref #104
~The main downside here is having eg. the second window not trigger a centering.~ It will now center the tiling if it was centered before the layout.
> tiling: maximize the space when removing/adding windows

- README.md
- kludges.js
- stackoverlay.js
- tiling.js
This adds better support for workspaces-only-on-primary:
- moving windows with grab
- moving between monitors (without or without a window)
- Only works properly when secondary monitors are above or below primary :-1: (Though this isn't a new bug) (I'm seeing some weirdness using a nested gnome-shell to test, which I'm unable to reproduce in a real session).
We now only handle grabs in `window-entered-monitor`, which should hopefully solve windows accidentally moving between workspaces when changing monitors :tada: 
~I opted to remove setting  `workspaces-only-on-primary` to false as a recommended setting, as things should honestly work a bit smoother with workspace only on primary.~
> Better workspaces-only-on-primary support

- examples/keybindings.js
- tiling.js
- topbar.js
- utils.js
- Remove the `Set ...` buttons, just update the name on the fly instead
- Remove the color selection, didn't really work all that great. Perhaps rather add 3 sliders ala. the volume?
- Add buttons to select other workspace settings
> Modernize the workspace menu

- kludges.js
add global.display.get_monitor_neighbor_index that uses global.screen.get_monitor_neighbor_index
Meta.DisplayDirection = Meta.ScreenDirection;
> Gnome 3.28 compatibility fixes for #182

- README.md
- install.sh
- set-recommended-gnome-shell-settings.sh
- uninstall.sh
Apparently `gnome-extensions enable $uuid` doesn't work without a restart (at least not consistently). Use the same trick as in [gnome-shell-mode](https://github.com/paperwm/gnome-shell-mode/blob/master/local/gnome-shell-mode/bootstrap.js) to send js to get gnome-shell to load the extension.
Also add an uninstall script, which simply disables paperwm and removes the installed symlink. One would think `gnome-extensions uninstall` would be suitable, but unfortunately it doesn't handle symlink installs in a sane manner. It will actually go into the symlink, remove _everything_ recurively, including hidden directories like `.git`....,  and after it has wrecked havoc remove the directory :( 
ref #230
> Enable on install

- Settings.ui
- schemas/org.gnome.shell.extensions.org-scrollwm.gschema.xml
Changes "GNOME Shell" name capitalization to match upstream project name: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/README.md
> gnome shell background -> GNOME Shell background

- README.md
Small fixups with duplicated sentences in `README`. The two paragraphs are combined.
> Remove and combine duplicated sentences in README

- uninstall.sh
fixes the errors
"rm: cannot remove '/home/reacocard/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org': Is a directory"
and
"rm: remove write-protected regular file '/home/reacocard/.local/share/gnome-shell/extensions/paperwm@hedning:matrix.org/.git/objects/pack/pack-3c3158f6621fdd04f2b4c3870a93934d2f6b695f.pack'?"
by adding -r and -f respectively to rm.
> fix uninstall.sh

- tiling.js
Removes small bottom border on workspace label that is visible when not covered by the top bar (especially on multi-monitor setups).
Before:
After:
> fix workspace-label border

- examples/keybindings.js
If the focused window is not stacked, it stacks it at the bottom of an adjacent column
If the focused window is stacked, it moves it out into its own column.
> Add "StackUnstack" action in Examples.

- liveAltTab.js
Looks like this was recently changed here: bcd92857ae267bb561ee5e96591eeaaf606bd81d
Without this the last line would raise an error because `actor` is undefined.
> Set actor variable for use after `if`

- navigator.js
This simple change will disable timeouts when using keybindings without modifiers for switching between windows, eg. Volume Up/Down keys. This resolves https://github.com/paperwm/PaperWM/issues/355.
> Remove navigator timeout for keybindings without mods
